export const ADMIN_ADD_QUESTION_REQUEST='ADMIN_ADD_QUESTION_REQUEST'
export const ADMIN_ADD_QUESTION_SUCCESS='ADMIN_ADD_QUESTION_SUCCESS'
export const ADMIN_ADD_QUESTION_FAIL='ADMIN_ADD_QUESTION_FAIL'


export const ADMIN_ALL_QUESTION_REQUEST='ADMIN_ALL_QUESTION_REQUEST'
export const ADMIN_ALL_QUESTION_SUCCESS='ADMIN_ALL_QUESTION_SUCCESS'
export const ADMIN_ALL_QUESTION_FAIL='ADMIN_ALL_QUESTION_FAIL'


export const EDIT_QUESTION_REQUEST='EDIT_QUESTION_REQUEST'
export const EDIT_QUESTION_SUCCESS='EDIT_QUESTION_SUCCESS'
export const EDIT_QUESTION_FAIL='EDIT_QUESTION_FAIL'




export const ADMIN_DELETE_QUESTION_REQUEST='ADMIN_DELETE_REQUEST'
export const ADMIN_DELETE_QUESTION_SUCCESS='ADMIN_DELETE_SUCCESS'
export const ADMIN_DELETE_QUESTION_FAIL='ADMIN_DELETE_FAIL'


export const ALL_PREMIUM_DETAILS_REQUEST='ALL_PREMIUM_DETAILS_REQUEST'
export const ALL_PREMIUM_DETAILS_SUCCESS='ALL_PREMIUM_DETAILS_SUCCESS'
export const ALL_PREMIUM_DETAILS_FAIL='ALL_PREMIUM_DETAILS_FAIL'



export const ADD_PREMIUM_REQUEST='ADD_PREMIUM_REQUEST'
export const ADD_PREMIUM_SUCCESS='ADD_PREMIUM_SUCCESS'
export const ADD_PREMIUM_FAIL='ADD_PREMIUM_FAIL'
