export const ALL_MATCHES_REQUEST='ALL_MATCHES_REQUEST';
export const ALL_MATCHES_SUCCESS='ALL_MATCHES_SUCCESS';
export const ALL_MATCHES_FAIL='ALL_MATCHES_FAIL';
export const CLEAR_ERRORS='CLEAR_ERRORS'


export const MATCH_DETAILS_REQUEST='MATCH_DETAILS_REQUEST'
export const MATCH_DETAILS_SUCCESS='MATCH_DETAILS_SUCCESS'
export const MATCH_DETAILS_FAIL='MATCH_DETAILS_FAIL'