export const ALL_MATCHES_REQUEST='ALL_MATCHES_REQUEST';
export const ALL_MATCHES_SUCCESS='ALL_MATCHES_SUCCESS';
export const ALL_MATCHES_FAIL='ALL_MATCHES_FAIL';


export const CLEAR_ERRORS='CLEAR_ERRORS'


export const MATCH_DETAILS_REQUEST='MATCH_DETAILS_REQUEST'
export const MATCH_DETAILS_SUCCESS='MATCH_DETAILS_SUCCESS'
export const MATCH_DETAILS_FAIL='MATCH_DETAILS_FAIL'



export const MATCH_FAV_REQUEST='MATCH_FAV_REQUEST'
export const MATCH_FAV_SUCCESS='MATCH_FAV_SUCCESS'
export const MATCH_FAV_FAIL='MATCH_FAV_FAIL'
export const MATCH_FAV_CLEAR_ERROR='MATCH_FAV_CLEAR_ERROR'



export const MATCH_SENTREQUEST_REQUEST='MATCH_SENTREQUEST_REQUEST'
export const MATCH_SENTREQUEST_SUCCESS='MATCH_SENTREQUEST_SUCCESS'
export const MATCH_SENTREQUEST_FAIL='MATCH_SENTREQUEST_FAIL'
export const MATCH_SENTREQUEST_CLEAR_ERROR='MATCH_SENTREQUEST_CLEAR_ERROR'



export const ALL_SENT_REQUESTS_REQUEST='ALL_SENT_REQUESTS_REQUEST'
export const ALL_SENT_REQUESTS_SUCCESS='ALL_SENT_REQUESTS_SUCCESS'
export const ALL_SENT_REQUESTS_FAIL='ALL_SENT_REQUESTS_FAIL'



export const ALL_RECEIVED_REQUESTS_REQUEST='ALL_RECEIVED_REQUESTS_REQUEST'
export const ALL_RECEIVED_REQUESTS_SUCCESS='ALL_RECEIVED_REQUESTS_SUCCESS'
export const ALL_RECEIVED_REQUESTS_FAIL='ALL_RECEIVED_REQUESTS_FAIL'



