export const USER_LOGIN_REQUEST ='USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS='USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL= 'USER_LOGIN_FAIL'
export const USER_LOGOUT='USER_LOGOUT'


export const USER_REGISTER_REQUEST ='USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS='USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL= 'USER_REGISTER_FAIL'



export const USER_LIST_REQUEST ='USER_LIST_REQUEST'
export const USER_LIST_SUCCESS='USER_LIST_SUCCESS'
export const USER_LIST_FAIL= 'USER_LIST_FAIL'



export const USER_UPDATE_PROFILE_REQUEST ='USER_UPDATE_PROFILE_REQUEST'
export const USER_UPDATE_PROFILE_SUCCESS='USER_UPDATE_PROFILE_SUCCESS'
export const USER_UPDATE_PROFILE_FAIL= 'USER_UPDATE_PROFILE_FAIL'
export const USER_UPDATE_PROFILE_RESET='USER_UPDATE_PROFILE_RESET'


export const USER_UPDATE_PASSWORD_REQUEST='USER_UPDATE_PASSWORD_REQUEST'
export const USER_UPDATE_PASSWORD_SUCCESS='USER_UPDATE_PASSWORD_SUCCESS'
export const USER_UPDATE_PASSWORD_FAIL='USER_UPDATE_PASSWORD_FAIL'



export const FORGOT_PASSWORD_REQUEST='FORGOT_PASSWORD_REQUEST'
export const FORGOT_PASSWORD_SUCCESS='FORGOT_PASSWORD_SUCCESS'
export const FORGOT_PASSWORD_FAIL='FORGOT_PASSWORD_FAIL'

export const RESET_PASSWORD_REQUEST='RESET_PASSWORD_REQUEST'
export const RESET_PASSWORD_SUCCESS='RESET_PASSWORD_SUCCESS'
export const RESET_PASSWORD_FAIL='RESET_PASSWORD_FAIL'


export const ALL_PREMIUMS_DETAILS_REQUEST='ALL_PREMIUM_DETAILS_REQUEST'
export const ALL_PREMIUMS_DETAILS_SUCCESS='ALL_PREMIUM_DETAILS_SUCCESS'
export const ALL_PREMIUMS_DETAILS_FAIL='ALL_PREMIUM_DETAILS_FAIL'

export const PAYEMENT_REQUEST='PAYMENT_REQUEST'
export const PAYEMENT_SUCCESS='PAYMENT_SUCCESS'
export const PAYEMENT_FAIL='PAYMENT_FAIL'

export const ALL_FRIENDS_REQUEST='ALL_FRIENDS_REQUEST'
export const ALL_FRIENDS_SUCCESS='ALL_FRIENDS_SUCCESS'
export const ALL_FRIENDS_FAIL='ALL_FRIENDS_FAIL'
